apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sonar-ts-plugin
  description: null
  annotations:
    github.com/project-slug: pats/SonarTsPlugin
  tags:
    - frontend
    - codesnoop
spec:
  owner: pats
